momentGW/rpa.py
This adds a parameter `compress` to `rpa.build_se_moments_drpa` which determines how many attempts will be made to compress the low-rank representation within RIRPA, bringing the optionality here in line with Vayesta after [this](https://github.com/BoothGroup/Vayesta/pull/77) PR.
This should reduce the overhead from attempted compression of the low-rank representation to basically nothing. I haven't got `dyson` set up on my current machine so haven't run the tests locally, though given the nature of it it's hopefully low-risk. Note that this will currently result in no compression attempts unless `compress` is passed as a kwarg to `GW.build_se_moments`, but that's optimal for current system sizes anyway.
=> Update for control of low-rank compression in RIRPA functionality.

momentGW/base.py, momentGW/evgw.py, momentGW/gw.py, momentGW/ints.py, momentGW/qsgw.py, momentGW/rpa.py, momentGW/scgw.py, momentGW/tda.py, tests/test_gw.py, tests/test_scgw.py
- Adds `ints.py` with a class `Integrals`, which should simplify the interfaces going forward when we add k-points and THC. I will probably subclass this as `KIntegrals` and `THCIntegrals`.
- Deprecates `vhf_df` - I may want to reimplement this later but it has been causing issues in the current implementation.
- Fixes a bug that caused compressed integrals to be used for evaluating the Fock matrix when `fock_loop=True`.
=> `Integrals` class

momentGW/base.py, momentGW/evgw.py, momentGW/fock.py, momentGW/gw.py, momentGW/ints.py, momentGW/qsgw.py, momentGW/scgw.py, momentGW/util.py, tests/test_gw.py, tests/test_scgw.py
The fock build functions are now part of the `Integrals` classes, making THC integration easier. Also `build_se_static` now uses these functions to build the exchange matrix.
=> Migrates the fock build into the Integrals class

momentGW/energy.py, momentGW/gw.py, momentGW/pbc/gw.py, momentGW/pbc/scgw.py, momentGW/scgw.py, tests/test_kgw.py
Reports total energies using the Galitskii-Migdal formula. Currently reports this using both G0 and the G resulting from `solve_dyson`. I think this happily lives inside `solve_dyson`, because then the energies are reported every time a method solves for a Green's function - though maybe qsGW needs some additional reporting.
=> Total energies

momentGW/__init__.py, momentGW/evgw.py, momentGW/gw.py, momentGW/pbc/gw.py, momentGW/pbc/tda.py, momentGW/qsgw.py, momentGW/rpa.py, momentGW/scgw.py, momentGW/tda.py, momentGW/thc.py
Changes naming conventions so that they specify dTDA and dRPA where intended, and allows `polarizability` input keyword to be case-insensitive.
=> Clarify naming convention for dTDA and dRPA

tests/test_kugw.py
The `Test_KUGW.test_dtda_vs_supercell` test in `tests/test_kugw.py` was flaky - one of the QP energies was sometimes different, maybe some instability somewhere. I've reduced the number of moments to hopefully improve it.
=> Improve flaky test

momentGW/ints.py, momentGW/pbc/ints.py, tests/test_evugw.py
I used `einsum` for the integral transformations whilst figuring out the algorithms. I forgot to replace these with calls to `pyscf.ao2mo._ao2mo.nr_e2` and `pyscf.ao2mo._ao2mo.r_e2`, which are faster and can exploit symmetry in the AO basis integrals.
This PR replaces the `einsum` calls, which offers large optimisations, as the integral transformations can often constitute a large portion of the run time.
=> Optimisations for integral transformations

momentGW/ints.py, momentGW/pbc/ints.py
- Removes another `einsum` call in favour of the PySCF optimised routines.
- Replaces an `einsum` that falls back to `numpy` with a `dot` call
There are some similar optimisations available for k-space, but I haven't done any benchmarking for that yet, I'll wait for all that stuff to settle post RPA merge.
=> More optimisations for integral transformations

momentGW/ints.py, momentGW/pbc/ints.py, momentGW/tda.py, momentGW/uhf/tda.py
Previously we constructed the entire `eta` array with shape `(nmo, nmom, nmo, nmo)` in the memory before the convolution with the moments of the Green's function. This is a huge waste of memory, as each slice in second axis (`nmom`) can be treated separably.
- Adds `eta_orders` argument to `convolve` function to specify which orders of `eta` it's being called for.
- Changes `build_se_moments` to construct the moments for each order of `eta` instead of globally.
This depends on #43, please merge after that. As with #43, I have not propagated these changes to the k-space implementation yet, in case things change before the RPA is merged.
=> Direct DD moment convolution

momentGW/energy.py, momentGW/gw.py, momentGW/pbc/gw.py, momentGW/pbc/uhf/gw.py, momentGW/uhf/gw.py
The GM energy with a correlated G can be done in N^3 rather than N^4:
- Reimplements GM energy at N^3
- Enables GM energy with correlated G to be reported for all methods
=> Optimisations to Galitskii-Migdal energy

momentGW/bse.py, momentGW/energy.py, momentGW/fock.py, momentGW/gw.py, momentGW/ints.py, momentGW/pbc/fock.py, momentGW/pbc/gw.py, momentGW/pbc/ints.py, momentGW/pbc/kpts.py, momentGW/pbc/qsgw.py, momentGW/pbc/tda.py, momentGW/pbc/thc.py, momentGW/pbc/uhf/fock.py, momentGW/pbc/uhf/gw.py, momentGW/pbc/uhf/ints.py, momentGW/pbc/uhf/qsgw.py, momentGW/pbc/uhf/tda.py, momentGW/qsgw.py, momentGW/rpa.py, momentGW/tda.py, momentGW/thc.py, momentGW/uhf/fock.py, momentGW/uhf/gw.py, momentGW/uhf/ints.py, momentGW/uhf/qsgw.py, momentGW/uhf/rpa.py, momentGW/uhf/tda.py, momentGW/util.py
- Implements internal `einsum` that always optimises contraction order and dispatches via `DGEMM` where possible
- Swaps out all `einsum` calls for the new internal function
Note: unlike `pyscf.lib.einsum`, this function calls `np.core.einsumfunc._parse_einsum_input` to parse the input arguments. This means that any `Ellipsis` in the subscripts are swapped out internally. This will prevent the problem we had where `einsums` written to be agnostic w.r.t spin or k-space won't just be dispatched via unoptimised `numpy.einsum` calls any more.
=> Changes to handling of `einsum`

momentGW/__init__.py, momentGW/fsgw.py, momentGW/pbc/__init__.py, momentGW/pbc/fsgw.py, momentGW/pbc/uhf/__init__.py, momentGW/pbc/uhf/fsgw.py, momentGW/uhf/__init__.py, momentGW/uhf/fsgw.py, momentGW/uhf/qsgw.py, tests/test_fsgw.py, tests/test_fskgw.py, tests/test_fskugw.py, tests/test_fsugw.py
This PR implements a flavour of self-consistent GW that self-consistently solves for the density using a Fock matrix accompanied by a self-energy calculated at the level of GW, and then finds a new GW self-energy using the updated MOs defining that density.
=> Fock self-consistent GW

momentGW/pbc/ints.py
- Fixes bug in `pbc.ints.KIntegrals.get_j` and `pbc.ints.KIntegrals.get_k` where full auxiliary size was used for arrays that may be blocked over or compressed.
- Performs some optimisations to `pbc.ints.KIntegrals` to match #42 and #43 
This code is getting a bit messy, once the solids stuff is in a nice place we should look into cleaning it up
=> Optimisations and fixes for PBC ints

momentGW/gw.py, momentGW/ints.py, momentGW/uhf/ints.py, tests/test_fsgw.py, tests/test_qsgw.py
Implements a more rigorous construction of the static self-energy.
=> Self-energy construction fixes

momentGW/__init__.py, momentGW/bse.py, momentGW/fock.py, momentGW/gw.py, momentGW/pbc/fock.py, momentGW/pbc/gw.py, momentGW/pbc/uhf/fock.py, momentGW/pbc/uhf/gw.py, momentGW/uhf/fock.py, momentGW/uhf/gw.py, tests/test_kugw.py, tests/test_sckugw.py, tests/test_ugw.py
Implement solvers for Fock loops with proper inheritance. Merge after #50 and #51.
- Fock loops use solver classes with inheritance
- `solve_dyson` functions use these solvers additionally for the chemical potential searching
- Adds some R vs. U Fock loop tests
=> Fock loop solvers

momentGW/evgw.py, momentGW/scgw.py, momentGW/util.py, tests/test_evgw.py, tests/test_gw.py, tests/test_scugw.py, tests/test_ugw.py
We have been applying DIIS to moments by scaling the moments to account for the fact that they are on wildly different numerical ranges. I was originally doing something like:
```
moments = ...
moments_scaled = scale(moments)
moments_error = get_error(moments_scaled)
moments_scaled = diis(moments_scaled, moments_error)
moments = unscale(moments_scaled)
```
however this is also very numerically unstable. I've changed this to something like:
```
moments = ...
moments_error = get_error(moments)
moments_error_scaled = scale(moments_error)
moments = diis(moments, moments_error_scaled)
```
such that the DIIS coefficients are calculated using the scaled errors, but the moments that are therein linearly combined are never scaled/unscaled, avoiding the loss of precision.
=> Fix scaled DIIS

momentGW/base.py, momentGW/pbc/base.py, momentGW/pbc/uhf/base.py, momentGW/uhf/base.py
This PR improves the `_gf_to_mo_energy` functions. Originally these functions found the poles which best overlap with the MOs and used them as new MO energies, which allowed poles to be used multiple times for the same MO, introducing an artificial degeneracy in the new MO energies. This only happened for considerably non-Koopmans'-like states, and triggered the ambiguous `Inconsistent quasiparticle weights` warning.
The new implementation uses some heuristic to make unique assignments on each MO. This removes the aforementioned warning which is now impossible.
This PR also improves the inheritance for these functions such that there is a single implementation of the new algorithm in `BaseGW`.
=> Improve `_gf_to_mo_energy`

.pre-commit-config.yaml, .pre-commit-hooks.yaml, README.md, pyproject.toml
Adds pre-commit hooks to execute the formatting and linting stack before the commit. For `ssort`, `isort`, and `black`, this will change the committed code. I believe for `flake8` this will just prevent a commit in the case of errors.
Note that you'll need to run
```
pip install pre-commit
pre-commit install
```
to get them working.
=> Add pre-commit hooks

momentGW/base.py, momentGW/bse.py, momentGW/uhf/base.py
Adds a `_convert_mf` method that is called as
```
self._scf = self._convert_mf(mf)
```
when initialising the solvers.  This allows one to i.e. call `UGW(mf)` where `mf` is restricted, and the solver will first convert it to unrestricted.
=> Add hooks for converting the mean-field

momentGW/base.py, momentGW/bse.py, momentGW/evgw.py, momentGW/fock.py, momentGW/fsgw.py, momentGW/pbc/base.py, momentGW/pbc/evgw.py, momentGW/pbc/fsgw.py, momentGW/pbc/gw.py, momentGW/pbc/qsgw.py, momentGW/pbc/scgw.py, momentGW/pbc/uhf/evgw.py, momentGW/pbc/uhf/fsgw.py, momentGW/pbc/uhf/gw.py, momentGW/pbc/uhf/qsgw.py, momentGW/pbc/uhf/scgw.py, momentGW/qsgw.py, momentGW/uhf/evgw.py, momentGW/uhf/fsgw.py, momentGW/uhf/qsgw.py, momentGW/uhf/scgw.py, momentGW/util.py
Refactors the solver options internals, now each solver has
- `_defaults`: determined at class declaration, contains the default options for the solver
- `_opts`: set at object initialisation, copied from `_defaults` and updated accordingly
`__getattr__` and `__setattr__` are implemented on the `Base` class so that nothing API-related changes. This slightly cleaner but also facilitates `sphinx` documentation i've been messing with a bit better.
=> Refactor solver options

momentGW/base.py, momentGW/fock.py, momentGW/ints.py, momentGW/pbc/base.py, momentGW/pbc/ints.py, momentGW/pbc/kpts.py, momentGW/pbc/rpa.py, momentGW/pbc/tda.py, momentGW/pbc/thc.py, momentGW/pbc/uhf/ints.py, momentGW/pbc/uhf/tda.py, momentGW/thc.py, momentGW/uhf/ints.py, momentGW/uhf/tda.py, tests/test_kthcgw.py
Caches some properties that don't have O(1) overhead using `functools.cached_property`. Also ensures that properties like this that are not elegantly cacheable are instantiated outside of rate-limiting loops.
Some of the integrals code is getting a bit messy now... maybe a refactor in the future would be nice
=> Property caching

tests/test_evgw.py, tests/test_gw.py, tests/test_kthcgw.py, tests/test_qsgw.py, tests/test_thcgw.py
CI began to fail due to a series of small differences within the some regressions tests (order `e-07`). As no new code was pushed and due to the relatively small size of the differences, most likely due to a change in the github nodes. The values have been updated to reflect these new results for the tests, while also lowering these tests so that the threshold for an error is `e-06` rather than `e-07`.
=> CI update fix

pyproject.toml
Freezes the version of `dyson` ahead of the incoming refactor, which will need API changes
=> Freeze `dyson` version
